spring:
  #Database
  datasource:
    url: jdbc:mysql://localhost:3306/plr_movie_web
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Flyway
  flyway:
    enabled: false